# Generated by Django 4.1.4 on 2024-03-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_channel_channel_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='bussiness_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='facebook',
            field=models.URLField(default='https://facebook.com'),
        ),
        migrations.AddField(
            model_name='channel',
            name='instagram',
            field=models.URLField(default='https://instagram.com'),
        ),
        migrations.AddField(
            model_name='channel',
            name='make_bussiness_email_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='twitter',
            field=models.URLField(default='https://twitter.com'),
        ),
        migrations.AddField(
            model_name='channel',
            name='website',
            field=models.URLField(default='https://my-website.com'),
        ),
    ]
