# Generated by Django 4.1.4 on 2024-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_channel_bussiness_email_channel_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='bussiness_location',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='make_bussiness_location_public',
            field=models.BooleanField(default=False),
        ),
    ]
