# Generated by Django 4.1.4 on 2024-03-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0006_channel_bussiness_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='bussiness_email',
            new_name='business_email',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='bussiness_location',
        ),
        migrations.AddField(
            model_name='channel',
            name='business_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
