# Generated by Django 4.1.4 on 2024-03-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_rename_bussiness_email_channel_business_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='make_bussiness_email_public',
            new_name='make_business_email_public',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='make_bussiness_location_public',
            new_name='make_business_location_public',
        ),
    ]
