# Generated by Django 4.1.4 on 2024-03-22 20:58

import channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_community'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Community', 'verbose_name_plural': 'Community Posts'},
        ),
        migrations.AlterField(
            model_name='community',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=channel.models.user_directory_path),
        ),
    ]
