# Generated by Django 4.1.4 on 2024-03-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0012_commmunitycomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commmunitycomments',
            name='comment',
            field=models.CharField(max_length=10000),
        ),
    ]
