# Generated by Django 4.1.4 on 2024-03-27 18:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0013_alter_commmunitycomments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_art',
            field=models.ImageField(blank=True, default='channel-art.jpg', null=True, upload_to=core.models.user_directory_path),
        ),
    ]
